version: '3.8'

services:
  bot:
    build:
      dockerfile: dockerfile
    env_file:
      - .env
    command: bash -c "
      source src/.venv/bin/activate
      && cd src
      && python -m src.main
      "
  
  
  
  #  migration:
  #    build:
  #      dockerfile: dockerfile
  #    command: bash -c "aerich upgrade"
  #    volumes:
  #      - .:/usr/src
  #    depends_on:
  #      - db

#  db:
#    image: postgres:14
#    environment:
#      - POSTGRES_DB=devdb
#      - POSTGRES_USER=devdb
#      - POSTGRES_PASSWORD=password
#    ports:
#      - "5432:5432"
#    volumes:
#      - db-dev:/var/lib/postgresql/data


volumes:
  db-dev: { }
