version: '3.8'

services:
  bot:
    build:
      dockerfile: dockerfile
    deploy:
      replicas: 0
    env_file:
      - .env

  #  migration:
  #    build:
  #      dockerfile: dockerfile
  #    command: bash -c "aerich upgrade"
  #    volumes:
  #      - .:/usr/src
  #    depends_on:
  #      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=dominions
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-dev:/var/lib/postgresql/data


volumes:
  db-dev: { }
