name: Deploy

on:
  push:
    tags:
      - "*.*"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: docker/build-push-action@v2
        with:
          repository: stvnksslr/dominions-slack-bot
          tag_with_ref: true
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}